allprojects {
    repositories {
        google()
        mavenCentral()
    }
}

rootProject.buildDir = "../build"
subprojects {
    project.buildDir = "${rootProject.buildDir}/${project.name}"
}
subprojects {
    project.evaluationDependsOn(":app")
}

tasks.register("clean", Delete) {
    delete rootProject.buildDir
}

subprojects {
    def setNamespace = { p ->
        if (p.hasProperty('android')) {
            if (p.android.namespace == null) {
                p.android.namespace = p.group
            }
        }
    }

    project.plugins.withId('com.android.library') {
        setNamespace(project)
    }
    project.plugins.withId('com.android.application') {
        setNamespace(project)
    }
}
